const icons = { APS:'🛜', SW:'🌐', CAM:'🎥', RFID:'🏷️', MPC:'🖥️', SATO:'🖨️', LEXMARK:'📇' };
const home = document.getElementById('home');
const listView = document.getElementById('listView');
const racksView = document.getElementById('racksView');
const cards = document.getElementById('groupCards');
const table = document.getElementById('deviceTable');
const title = document.getElementById('listTitle');
const subtitle = document.getElementById('listSubtitle');
const total = document.getElementById('total');
const onlineTotal = document.getElementById('onlineTotal');
const offlineTotal = document.getElementById('offlineTotal');
const lastCheck = document.getElementById('lastCheck');
const onlyProblemsBtn = document.getElementById('onlyProblemsBtn');
const rfidPageBtn = document.getElementById('rfidPageBtn');
const racksBtn = document.getElementById('racksBtn');
const saveBtn = document.getElementById('saveBtn');
const addRowBtn = document.getElementById('addRowBtn');
const rackButtons = document.getElementById('rackButtons');
const selectedRackHeader = document.getElementById('selectedRackHeader');
const rackHeaderImage = document.getElementById('rackHeaderImage');
const rackTableBody = document.getElementById('rackTableBody');
const rackTableSubtitle = document.getElementById('rackTableSubtitle');
const addRackRowBtn = document.getElementById('addRackRowBtn');
const saveRackBtn = document.getElementById('saveRackBtn');
const statusCache = {};
let lastCheckAt = null, isChecking = false, currentGroup = null, selectedRack = null, selectedRackImage = null;
let sortState = { key: 'ip', direction: 'asc' };
const LOCATION_OPTIONS = ['ADMIN','AIRE','CAÑOS','CALIDAD','CELULARES','COMEDOR','FCT','GUARDIA','IA','INGENIERIA','IT','LABORATORIO','MANTENIMIENTO','MEDICO','MYT','NACIONALES','OFDEPOSITO','PRODUCCIÓN','SOLDADURA','SUM','TV'];
const TYPE_OPTIONS = ['APS','CORE','SW','CAM','RFID','MPC','SATO','LEXMARK','OTRO'];
const RACKS = [['01','IA DEPO'],['02','IA SALA'],['04','IA FONDO'],['05','NACIONALES'],['06','RESIDUOS'],['07','TELEVISION'],['Cel1','CEL01'],['Cel2','CEL02'],['08','NAC2'],['08b','MYT'],['09','EXPEDISION'],['09b','CALIDAD'],['10','MAT PRIMA'],['11','DEP RVF'],['12','AIRE 1'],['13','DARSENAS'],['14','AIRE 2'],['15','SALA BOMBAS'],['16','FCT'],['17','LABORATORIO'],['18','DEP NUEVO'],['19','NVR SALA'],['20','IA FONDO'],['tv1','TV 1'],['tv2','TV 2'],['tv3','TV 3'],['tv4','TV 4']];
function cloneDevices(source){return Object.fromEntries(Object.entries(source).map(([g,d])=>[g,d.map(x=>({...x}))]));}
let editableDevices=cloneDevices(DEVICES),rackData={};
function normalizeDevice(device,group){return {...device,ip:device.ip||'',hostname:device.hostname??device.name??'',name:undefined,type:device.type||(group==='SW'?'SW':group),location:device.location||'',connection:device.connection||'',group,newRow:device.newRow||false};}
function normalizeAllDevices(devices){const result={};Object.entries(devices||{}).forEach(([g,l])=>result[g]=Array.isArray(l)?l.map(d=>normalizeDevice(d,g)):[]);Object.keys(DEVICES).forEach(g=>{if(!Array.isArray(result[g]))result[g]=[]});return result;}
async function loadSavedConfig(){try{const saved=await window.monitorAPI.loadDeviceConfig();if(saved&&typeof saved==='object')editableDevices=normalizeAllDevices(saved);else{editableDevices=normalizeAllDevices(DEVICES);await saveConfig();}}catch(e){console.log('No se pudo cargar la configuración:',e.message);editableDevices=normalizeAllDevices(DEVICES);}}
async function saveConfig(){try{const clean={};Object.entries(editableDevices).forEach(([g,ds])=>clean[g]=ds.map(d=>{const c={...d};delete c.name;delete c.newRow;return c;}));await window.monitorAPI.saveDeviceConfig(clean);return true;}catch(e){console.log('No se pudo guardar la configuración:',e.message);return false;}}
async function loadRackConfig(){try{const saved=await window.monitorAPI.loadRackConfig();rackData=saved&&typeof saved==='object'?saved:{}}catch(e){console.log('No se pudo cargar la configuración de racks:',e.message);rackData={};}}
async function saveRackConfig(){try{await window.monitorAPI.saveRackConfig(rackData);return true}catch(e){console.log('No se pudo guardar la configuración de racks:',e.message);return false;}}
function setCardStatus(group,status){const card=[...cards.children].find(c=>c.dataset.group===group);if(!card)return;card.classList.remove('group-online','group-offline','group-checking');card.classList.add(`group-${status}`);}
function renderHome(){cards.innerHTML='';let count=0;Object.entries(editableDevices).forEach(([g,ds])=>{count+=ds.length;const card=document.createElement('div');card.className='card group-checking';card.dataset.group=g;card.innerHTML=`<div class="icon">${icons[g]||'🖧'}</div><h3>${g}</h3><p>${ds.length} equipos</p>`;card.onclick=()=>openGroup(g);cards.appendChild(card);});Object.entries(statusCache).forEach(([g,ds])=>setCardStatus(g,Object.values(ds).some(d=>!d.online)?'offline':'online'));total.textContent=count;updateTotals();}
function updateTotals(){let on=0,off=0;Object.values(statusCache).forEach(g=>Object.values(g).forEach(d=>d.online?on++:off++));onlineTotal.textContent=on;offlineTotal.textContent=off;}
function formatTime(date){return date.toLocaleTimeString('es-AR',{hour12:false});}
function updateClock(){document.getElementById('clock').textContent=`HORA ACTUAL: ${formatTime(new Date())}`;}
function updateLastCheck(){lastCheck.textContent=`ÚLTIMO PING: ${lastCheckAt?formatTime(lastCheckAt):'—'}`;}
function sortedDevices(group){const ds=[...(editableDevices[group]||[])],key=sortState.key,dir=sortState.direction==='asc'?1:-1;return ds.sort((a,b)=>{let av,bv;if(key==='status'){av=statusCache[group]?.[a.ip]?.online?1:0;bv=statusCache[group]?.[b.ip]?.online?1:0;}else if(key==='ip'){av=String(a.ip||'').split('.').map(n=>n.padStart(3,'0')).join('.');bv=String(b.ip||'').split('.').map(n=>n.padStart(3,'0')).join('.');}else{av=String(a[key]??'').toLocaleLowerCase('es');bv=String(b[key]??'').toLocaleLowerCase('es');}return av<bv?-dir:av>bv?dir:0;});}
function inputCell(value,field,placeholder=''){const i=document.createElement('input');i.className='cellInput';i.value=value||'';i.placeholder=placeholder;i.dataset.field=field;return i;}
function selectCell(value,field,options){const s=document.createElement('select');s.className='cellSelect';const vals=[...options];if(value&&!vals.includes(value))vals.unshift(value);vals.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v||'—';o.selected=v===value;s.appendChild(o);});return s;}
function renderTable(group,statuses){table.innerHTML='';sortedDevices(group).forEach(device=>{const state=statuses?.[device.ip],tr=document.createElement('tr');tr.dataset.deviceIndex=editableDevices[group].indexOf(device);const ip=document.createElement('td');ip.className='ip';if(device.newRow){const i=inputCell(device.ip,'ip','Nueva IP');i.classList.add('newIpInput');i.oninput=()=>device.ip=i.value.trim();ip.appendChild(i);}else ip.textContent=device.ip;const hn=document.createElement('td'),hi=inputCell(device.hostname,'hostname','HOSTNAME');hi.oninput=()=>device.hostname=hi.value;hn.appendChild(hi);const loc=document.createElement('td'),ls=selectCell(device.location,'location',LOCATION_OPTIONS);ls.onchange=()=>device.location=ls.value;loc.appendChild(ls);const con=document.createElement('td'),ci=inputCell(device.connection,'connection','Conexión');ci.oninput=()=>device.connection=ci.value;con.appendChild(ci);const st=document.createElement('td');st.innerHTML=state?(state.online?`<span class="status online"><span class="dot"></span>ONLINE · ${state.latency!=null?state.latency+' ms':'—'}</span>`:`<span class="status offline"><span class="dot"></span>OFFLINE${state.latency!=null?' · '+state.latency+' ms':''}</span>`):'<span class="status"><span class="dot unknown"></span>COMPROBANDO</span>';tr.append(ip,hn,loc,con,st);table.appendChild(tr);});}
function openGroup(group){currentGroup=group;sortState={key:'ip',direction:'asc'};racksView.classList.remove('active');home.classList.remove('active');listView.classList.add('active');title.textContent=group;subtitle.textContent=`${editableDevices[group].length} IPs registradas`;renderTable(group,statusCache[group]||null);updateSortMarks();}
function openProblems(){home.classList.remove('active');racksView.classList.remove('active');listView.classList.add('active');currentGroup=null;title.textContent='SOLO PROBLEMAS';const problems=[];Object.entries(editableDevices).forEach(([g,ds])=>ds.forEach(d=>{const st=statusCache[g]?.[d.ip];if(st&&!st.online)problems.push({...d,...st,group:g});}));subtitle.textContent=`${problems.length} IPs con error`;table.innerHTML='';problems.forEach(d=>{const tr=document.createElement('tr');tr.innerHTML=`<td class="ip">${d.ip}</td><td>${d.hostname||'<span class="muted">Sin hostname</span>'}</td><td>${d.location||'<span class="muted">—</span>'}</td><td>${d.connection||'<span class="muted">—</span>'}</td><td><span class="problemGroup">${d.group}</span> <span class="status offline"><span class="dot"></span>OFFLINE</span></td>`;table.appendChild(tr);});}
function cacheResults(result){Object.entries(result).forEach(([g,ds])=>{statusCache[g]={};let err=false;ds.forEach(d=>{statusCache[g][d.ip]=d;if(!d.online)err=true;});setCardStatus(g,err?'offline':'online');});updateTotals();}
async function checkAll(){if(isChecking)return;isChecking=true;Object.keys(editableDevices).forEach(g=>setCardStatus(g,'checking'));try{const r=await fetch('http://127.0.0.1:3000/api/all');if(!r.ok)throw Error();cacheResults(await r.json());lastCheckAt=new Date();updateLastCheck();if(listView.classList.contains('active')&&currentGroup&&editableDevices[currentGroup])renderTable(currentGroup,statusCache[currentGroup]);}catch(e){Object.keys(editableDevices).forEach(g=>setCardStatus(g,'offline'));}finally{isChecking=false;}}
async function checkGroup(group){if(!editableDevices[group])return;setCardStatus(group,'checking');try{const r=await fetch(`http://127.0.0.1:3000/api/group/${encodeURIComponent(group)}`);if(!r.ok)throw Error();const ds=await r.json();statusCache[group]={};let err=false;ds.forEach(d=>{statusCache[group][d.ip]=d;if(!d.online)err=true;});setCardStatus(group,err?'offline':'online');updateTotals();lastCheckAt=new Date();updateLastCheck();if(listView.classList.contains('active')&&currentGroup===group)renderTable(group,statusCache[group]);}catch(e){setCardStatus(group,'offline');}}
function updateSortMarks(){document.querySelectorAll('#listView th[data-sort]').forEach(th=>{const m=th.querySelector('.sortMark');m.textContent=th.dataset.sort===sortState.key?(sortState.direction==='asc'?' ▲':' ▼'):' ↕';});}
document.querySelectorAll('#listView th[data-sort]').forEach(th=>th.addEventListener('click',()=>{if(sortState.key===th.dataset.sort)sortState.direction=sortState.direction==='asc'?'desc':'asc';else{sortState.key=th.dataset.sort;sortState.direction='asc';}if(currentGroup)renderTable(currentGroup,statusCache[currentGroup]||null);updateSortMarks();}));
document.getElementById('backBtn').onclick=()=>{listView.classList.remove('active');racksView.classList.remove('active');home.classList.add('active');currentGroup=null;renderHome();};
document.getElementById('refreshBtn').onclick=()=>{if(currentGroup)checkGroup(currentGroup);else checkAll().then(openProblems);};
addRowBtn.onclick=()=>{if(!currentGroup)return;editableDevices[currentGroup].push({ip:'',hostname:'',type:currentGroup,location:'',connection:'',group:currentGroup,newRow:true});renderTable(currentGroup,statusCache[currentGroup]||null);subtitle.textContent=`${editableDevices[currentGroup].length} IPs registradas`;table.querySelector('.newIpInput')?.focus();};
saveBtn.onclick=async()=>{if(!currentGroup)return;const rows=[...table.querySelectorAll('tr')],current=editableDevices[currentGroup];rows.forEach(row=>{const d=current[Number(row.dataset.deviceIndex)];if(!d)return;const ins=row.querySelectorAll('input'),sels=row.querySelectorAll('select');if(d.newRow){if(ins[0])d.ip=ins[0].value.trim();if(ins[1])d.hostname=ins[1].value;if(ins[2])d.connection=ins[2].value;}else{if(ins[0])d.hostname=ins[0].value;if(ins[1])d.connection=ins[1].value;}if(sels[0])d.location=sels[0].value;});editableDevices[currentGroup]=current.filter(d=>d.ip||!d.newRow);const ok=await saveConfig();saveBtn.textContent=ok?'✓ GUARDADO':'⚠ ERROR';setTimeout(()=>saveBtn.textContent='💾 GUARDAR',1200);subtitle.textContent=`${editableDevices[currentGroup].length} IPs registradas`;renderHome();renderTable(currentGroup,statusCache[currentGroup]||null);};
function renderRacks(){rackButtons.innerHTML='';RACKS.forEach(([rack,location])=>{const b=document.createElement('button');b.className='rackCard';b.dataset.rack=rack;b.innerHTML=`<strong>${rack}</strong><span>${location}</span>`;b.onclick=()=>selectRack(rack,location,b);rackButtons.appendChild(b);});}
function rackRowsFor(rack){if(!Array.isArray(rackData[rack]))rackData[rack]=[];return rackData[rack];}
function rackInput(value,field,placeholder=''){const i=document.createElement('input');i.className='rackCellInput';i.value=value||'';i.placeholder=placeholder;i.dataset.field=field;return i;}
function renderRackTable(rack,location){rackTableBody.innerHTML='';const rows=rackRowsFor(rack);rows.forEach((row,index)=>{const tr=document.createElement('tr');tr.dataset.index=index;['rack','sector','patch','sw','boca','marca','descripcion','hostname','ip'].forEach(f=>{const td=document.createElement('td'),i=rackInput(row[f],f,f==='rack'?rack:'');i.oninput=()=>row[f]=i.value;td.appendChild(i);tr.appendChild(td);});rackTableBody.appendChild(tr);});if(!rows.length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="9" class="empty">No hay equipos cargados en este rack. Use “AGREGAR FILA”.</td>';rackTableBody.appendChild(tr);}rackTableSubtitle.textContent=`${rows.length} equipos registrados`;}
async function selectRack(rack,location,button){selectedRack=rack;document.querySelectorAll('.rackCard').forEach(el=>el.classList.remove('selected'));button.classList.add('selected');selectedRackHeader.textContent=`RACK ${rack} - ${location}`;rackHeaderImage.removeAttribute('src');rackHeaderImage.classList.remove('visible');selectedRackImage=await window.monitorAPI.loadRackImage(rack);if(selectedRackImage){rackHeaderImage.src=selectedRackImage;rackHeaderImage.classList.add('visible');}renderRackTable(rack,location);}
function openRacks(){home.classList.remove('active');listView.classList.remove('active');racksView.classList.add('active');currentGroup=null;selectedRack=null;selectedRackHeader.textContent='SELECCIONE UN RACK';rackHeaderImage.removeAttribute('src');rackHeaderImage.classList.remove('visible');rackTableBody.innerHTML='<tr><td colspan="9" class="empty">Seleccione un rack para ver sus equipos.</td></tr>';rackTableSubtitle.textContent='Seleccione un rack para ver sus equipos';if(!rackButtons.children.length)renderRacks();}
function closeRacks(){racksView.classList.remove('active');home.classList.add('active');selectedRack=null;selectedRackImage=null;rackHeaderImage.removeAttribute('src');rackHeaderImage.classList.remove('visible');document.querySelectorAll('.rackCard').forEach(el=>el.classList.remove('selected'));renderHome();}
addRackRowBtn.onclick=()=>{if(!selectedRack)return;if(!Array.isArray(rackData[selectedRack]))rackData[selectedRack]=[];const location=RACKS.find(([r])=>r===selectedRack)?.[1]||'';rackData[selectedRack].push({rack:selectedRack,sector:location,patch:'',sw:'',boca:'',marca:'',descripcion:'',hostname:'',ip:''});renderRackTable(selectedRack,location);rackTableBody.querySelectorAll('tr')[rackTableBody.querySelectorAll('tr').length-1]?.querySelector('input')?.focus();};
saveRackBtn.onclick=async()=>{if(!selectedRack)return;const rows=[...rackTableBody.querySelectorAll('tr[data-index]')],current=rackData[selectedRack]||[];rows.forEach(row=>{const item=current[Number(row.dataset.index)];if(item)row.querySelectorAll('input').forEach(i=>item[i.dataset.field]=i.value);});const ok=await saveRackConfig();saveRackBtn.textContent=ok?'✓ GUARDADO':'⚠ ERROR';setTimeout(()=>saveRackBtn.textContent='💾 GUARDAR',1200);renderRackTable(selectedRack,RACKS.find(([r])=>r===selectedRack)?.[1]||'');};
onlyProblemsBtn.onclick=openProblems;rfidPageBtn.onclick=()=>window.monitorAPI.openRfidPages();racksBtn.onclick=openRacks;document.getElementById('racksBackBtn').onclick=closeRacks;rackHeaderImage.onclick=()=>{if(selectedRack)window.monitorAPI.openRackImage(selectedRack);};
function init(){updateClock();setInterval(updateClock,1000);}async function start(){await loadSavedConfig();await loadRackConfig();init();renderHome();updateLastCheck();checkAll();setInterval(checkAll,180000);}start();
