name: Construir Monitor Red para Windows

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependencias
        run: npm install
      - name: Construir EXE
        run: npm run build:win
      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: Monitor-Red-Windows
          path: dist/*.exe
          if-no-files-found: error
